name: Build Operator

on:
  workflow_dispatch:
    inputs:
      commitRef:
        description: The branch, tag or commit hash to checkout
        default: main
        required: true

jobs:
  build-docker-container:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          tags: dockerxucheng/geth-operator:${{ github.event.inputs.commitRef }}
          push: true
